### PR TITLE
Better error handling and fix file uploading.

### LINKED ISSUE #153: Window drag and drop file upload is broken
Probably the same issue as https://github.com/sarink/react-file-drop/issues/5

### PR DESCRIPTION
**Pull request by dignifiedquire**
Closes #153

### CODE REVIEW

File: app/controls/drag-drop.js [hunk 1]
```diff
@@ -1,10 +1,7 @@
-import API from 'ipfs-api'
 import notifier from 'node-notifier'
 import {join} from 'path'
 import {getIPFS, logger} from './../init'
```
Comment (diasdavid) [inline app/controls/drag-drop.js]: this works in Node.js due to transpilation, correct? Do we want to use two module systems in the same file? I'ld rather prefer to keep using CJS on Node.js side and ES6 for browser/ui side.

File: app/controls/drag-drop.js [hunk 2]
```diff
@@ -33,29 +30,35 @@ function notifyError (message) {
...
-    if (err || !res) {
-      logger.error(err)
-      notifyError(err || 'Failed to upload files')
-    }
 
-    logger.info('Uploading files', {files})
+  ipfs.add(files)
+    .then((res) => {
+      if (!res) {
+        notifyError('Failed to upload files')
```
Comment (diasdavid) [inline app/controls/drag-drop.js]: missing a `return` here

File: app/controls/drag-drop.js (hunk 1 above)
Comment (dignifiedquire) [inline app/controls/drag-drop.js]: The whole code base already uses es6 modules as everything gets transpiled anyway. If they are different repos we can have that differentiation, but in this case I'd rather have consistency in the repo. 

(Also this is not changed in this PR)

File: app/controls/drag-drop.js [hunk 3]
```diff
@@ -33,29 +30,35 @@ function notifyError (message) {
...
+
+      logger.info('Uploading files', {files})
 
-    res.forEach((file) => {
-      const url = `https://ipfs.io/ipfs/${file.Hash}`
-      clipboard.writeText(url)
-      filesUploaded.push(file)
+      res.forEach((file) => {
+        const url = `https://ipfs.io/ipfs/${file.Hash}`
+        clipboard.writeText(url)
```
Comment (diasdavid) [inline app/controls/drag-drop.js]: I guess this works because in a context of adding a directory, the 'last file' is actually the root hash of the whole dir. This doesn't work as nicely when a group of files is added, they needed to be wrapped in a dir object (like `ipfs add path -w`)

Comment (dignifiedquire) [inline app/controls/drag-drop.js]: This doesn't do directory uploads, as browsers still don't allow us to do it :cry:

Does `-w` work on the api?

File: app/controls/drag-drop.js (hunk 1 above)
Comment (diasdavid) [inline app/controls/drag-drop.js]: noted, why have `const clipboard = require('clipboard')` (line 8) then? :+1: for consistency

File: app/controls/open-browser.js [hunk 4]
```diff
@@ -1,23 +1,24 @@
 import ipc from 'electron-safe-ipc/host'
 import {apiAddrToUrl} from './utils'
-import {getIPFS} from './../init'
+import {logger, getIPFS} from './../init'
```
Comment (diasdavid) [inline app/controls/open-browser.js]: can we get the `logger` coming from a `config.js` file, along with other default values?

File: app/init.js [hunk 5]
```diff
@@ -21,36 +23,42 @@ if (config.isProduction) {
...
+    .then(next)
+
+  // ipfs.id((err, peer) => {
+  //  if (err) throw err
+  // lookupPretty(ipfs, peer.Addresses, (err, location) => {
+  //   if (err) throw err
+  //   statsCache.location = location && location.formatted
+  //   ipc.send('stats', statsCache)
+  // })
+  // })
```
Comment (diasdavid) [inline app/init.js]: do we still need this code?

File: app/controls/drag-drop.js (hunk 3 above)
Comment (dignifiedquire) [inline app/controls/drag-drop.js]: fixed :)

File: app/init.js (hunk 5 above)
Comment (dignifiedquire) [inline app/init.js]: yes, as soon as geoipfs is fixed

File: app/controls/open-browser.js (hunk 4 above)
Comment (dignifiedquire) [inline app/controls/open-browser.js]: No because it is not coming from the config but from the main index file that starts everything up

File: app/controls/drag-drop.js (hunk 1 above)
Comment (dignifiedquire) [inline app/controls/drag-drop.js]: hmmm no idea why that's there oO

Comment (dignifiedquire) [inline app/controls/drag-drop.js]: fixed

File: app/controls/drag-drop.js (hunk 3 above)
Comment (diasdavid) [inline app/controls/drag-drop.js]: > This doesn't do directory uploads, as browsers still don't allow us to do it 

But we can drag and drop several files to the tray icon :) 

> Does -w work on the api? 

It should :)

File: app/init.js (hunk 5 above)
Comment (diasdavid) [inline app/init.js]: got it, mind having a TODO and a link to the issue saying that?

Comment (dignifiedquire) [inline app/init.js]: done

**Comment by diasdavid** [comment]
LGTM.

There is no tests still, makes contributions really hard to do.

**Comment by dignifiedquire** [comment]
> There is no tests still, makes contributions really hard to do.

well you could write some :P
